package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'HackoladePlugins_Project_MariaDB_Repo_Build'
in the project with id = 'HackoladePlugins_Project_MariaDB', and delete the patch script.
*/
create(RelativeId("HackoladePlugins_Project_MariaDB"), BuildType({
    id("HackoladePlugins_Project_MariaDB_Repo_Build")
    name = "Build"

    vcs {
        root(RelativeId("HackoladePlugins_Project_MariaDB_PluginRepo"))
    }

    steps {
        nodeJS {
            name = "InstalL dependecies"
            shellScript = "npm ci"
        }
        nodeJS {
            name = "Run Linter"
            shellScript = "npm run lint"
        }
        nodeJS {
            name = "Package plugin"
            shellScript = "npm run package"
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

