package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'HackoladePlugins_Release'
in the project with id = 'HackoladePlugins', and delete the patch script.
*/
create(RelativeId("HackoladePlugins"), BuildType({
    id("HackoladePlugins_Release")
    name = "Release"

    enablePersonalBuilds = false
    type = BuildTypeSettings.Type.DEPLOYMENT
    maxRunningBuilds = 1
}))

