package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'MariaDb_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("MariaDb_Deploy")) {
    params {
        add {
            param("env.PLUGIN_NAME", "")
        }
    }
}
