package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.AZURE_STORAGE_ACCOUNT_SERVICE_PRINCIPAL_SECRET", "credentialsJSON:2646bf3b-d244-4150-a8f3-5ea7cb24e404", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
        update {
            password("env.AZURE_STORAGE_ACCOUNT_SERVICE_PRINCIPAL_SECRET", "credentialsJSON:05e9165e-5824-4abe-a1d5-0dad9120c825", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
        expect {
            password("env.GITHUB_ACCESS_TOKEN", "credentialsJSON:4c079522-f111-400c-8eb1-0fe4620bd5bc", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
        update {
            password("env.GITHUB_ACCESS_TOKEN", "credentialsJSON:72a94889-3f91-4237-ae61-cc4051326a28", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
        add {
            password("env.SLACK_ID", "credentialsJSON:5744ebae-e362-40d4-ae8b-ea612b8b9f3b", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }

    features {
        remove {
            githubConnection {
                id = "PROJECT_EXT_4"
                displayName = "GitHub.com"
                clientId = "cb10c5eb655b55614a2e"
                clientSecret = "credentialsJSON:130e3fd5-c108-4f2e-a1dc-1eb90230ade4"
            }
        }
    }
}
