package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            dockerRegistry {
                id = "PROJECT_EXT_3"
                name = "Docker Registry"
                userName = "bedletskyi"
                password = "credentialsJSON:59be1e15-f0d0-44c3-b683-47cf1674098d"
            }
        }
    }
}
