package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'HackoladePlugins_Project_MariaDBAlt'
in the project with id = 'HackoladePlugins_Project', and delete the patch script.
*/
create(RelativeId("HackoladePlugins_Project"), Project({
    id("HackoladePlugins_Project_MariaDBAlt")
    name = "MariaDB_alt"
}))

