package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the project with id = 'HackoladePlugins_Project'
from your code, and delete the patch script.
*/
deleteProject(RelativeId("HackoladePlugins_Project"))

