package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'MariaDb'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("MariaDb")) {
    params {
        expect {
            param("env.PLUGIN_NAME", "%system.teamcity.projectName%")
        }
        update {
            param("env.PLUGIN_NAME", "")
        }
        expect {
            param("env.PLUGIN_PATH", "./%system.teamcity.projectName%")
        }
        update {
            param("env.PLUGIN_PATH", "./%env.PLUGIN_NAME%")
        }
    }
}
