package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HackoladePlugins_Project_MariaDB_HttpsGithubComVitaliiBedletskyiMariaDBRefsHeadsRelease'
in the project with id = 'HackoladePlugins_Project_MariaDB', and delete the patch script.
*/
create(RelativeId("HackoladePlugins_Project_MariaDB"), GitVcsRoot({
    id("HackoladePlugins_Project_MariaDB_HttpsGithubComVitaliiBedletskyiMariaDBRefsHeadsRelease")
    name = "https://github.com/VitaliiBedletskyi/MariaDB#refs/heads/release"
    url = "https://github.com/VitaliiBedletskyi/MariaDB"
    branch = "refs/heads/release"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "VitaliiBedletskyi"
        password = "credentialsJSON:94c03b5b-2b09-4b69-afbf-6ddc4c5a61d7"
    }
    param("oauthProviderId", "PROJECT_EXT_4")
}))

