package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HackoladePlugins_Project_PluginsSettings'
in the project with id = 'HackoladePlugins_Project', and delete the patch script.
*/
create(RelativeId("HackoladePlugins_Project"), GitVcsRoot({
    id("HackoladePlugins_Project_PluginsSettings")
    name = "Plugins Settings"
    url = "https://github.com/VitaliiBedletskyi/teamcity-hackolade-plugins"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "VitaliiBedletskyi"
        password = "credentialsJSON:94c03b5b-2b09-4b69-afbf-6ddc4c5a61d7"
    }
}))

