package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Template
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with id = 'HackoladePlugins_Project_Build'
in the project with id = 'HackoladePlugins_Project', and delete the patch script.
*/
create(RelativeId("HackoladePlugins_Project"), Template({
    id("HackoladePlugins_Project_Build")
    name = "Build"

    maxRunningBuildsPerBranch = "*:1"

    steps {
        nodeJS {
            name = "Install dependecies"
            id = "RUNNER_7"
            shellScript = "npm ci"
        }
        nodeJS {
            name = "Run Linter"
            id = "RUNNER_8"
            shellScript = "npm run lint"
            dockerImage = "node:16"
        }
        nodeJS {
            name = "Package plugin"
            id = "RUNNER_9"
            shellScript = "npm run package"
            dockerImage = "node:16"
        }
    }
}))

