package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with id = '08050b68-4ea1-4580-9046-d2931ff6979b'
from your code, and delete the patch script.
*/
deleteTemplate(RelativeId("08050b68-4ea1-4580-9046-d2931ff6979b"))

