package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with id = '7074e11a-064a-4aa5-82ca-4f89f166fe1b'
from your code, and delete the patch script.
*/
deleteTemplate(RelativeId("7074e11a-064a-4aa5-82ca-4f89f166fe1b"))

