package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.NodeJSBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'PluginDeplyTemplate'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("PluginDeplyTemplate")) {
    expectSteps {
        nodeJS {
            name = "Install dependencies"
            id = "RUNNER_1"
            shellScript = "npm ci"
            dockerImage = "node:16"
        }
        nodeJS {
            name = "Package plugin"
            id = "RUNNER_3"
            shellScript = "npm run package"
            dockerImage = "node:16"
        }
    }
    steps {
        update<NodeJSBuildStep>(1) {
            id = "RUNNER_3"
            enabled = false
            clearConditions()
        }
        insert(2) {
            script {
                name = "Test step"
                id = "RUNNER_4"
                scriptContent = """echo "%teamcity.build.branch%""""
            }
        }
    }
}
