package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'PluginDeployTemplate'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("PluginDeployTemplate")) {
    expectSteps {
        script {
            name = "Setup plugin version"
            id = "RUNNER_1"
            scriptContent = """
                PLUGIN_NAME=${'$'}(npm pkg get name | tr -d '"')
                    PLUGIN_VERSION=${'$'}(npm pkg get version | tr -d '"')
                    
                    echo "##teamcity[setParameter name='env.PLUGIN_NAME' value=${'$'}PLUGIN_NAME]"
                    echo "##teamcity[setParameter name='env.PLUGIN_VERSION' value=${'$'}PLUGIN_VERSION]"
                "
            """.trimIndent()
            dockerImage = "node:16"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
        }
        nodeJS {
            name = "Install dependencies"
            id = "RUNNER_2"
            enabled = false
            shellScript = "npm ci"
            dockerImage = "node:16"
        }
        nodeJS {
            name = "Package plugin"
            id = "RUNNER_3"
            enabled = false
            shellScript = "npm run package"
            dockerImage = "node:16"
        }
        script {
            name = "Test print"
            id = "RUNNER_4"
            scriptContent = """
                echo "%env.PLUGIN_NAME%
                    echo "%env.PLUGIN_VERSION%
                "
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            id = "RUNNER_1"
            clearConditions()
            scriptContent = """
                PLUGIN_NAME=${'$'}(npm pkg get name | tr -d '"')
                PLUGIN_VERSION=${'$'}(npm pkg get version | tr -d '"')
                
                echo "##teamcity[setParameter name='env.PLUGIN_NAME' value=${'$'}PLUGIN_NAME]"
                echo "##teamcity[setParameter name='env.PLUGIN_VERSION' value=${'$'}PLUGIN_VERSION]"
            """.trimIndent()
        }
    }
}
