package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.nodeJS
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'PluginDeployTemplate'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("PluginDeployTemplate")) {
    expectSteps {
        nodeJS {
            name = "Install dependencies"
            id = "RUNNER_1"
            enabled = false
            shellScript = "npm ci"
            dockerImage = "node:16"
        }
        nodeJS {
            name = "Package plugin"
            id = "RUNNER_3"
            enabled = false
            shellScript = "npm run package"
            dockerImage = "node:16"
        }
        script {
            name = "Test step"
            id = "RUNNER_4"
            scriptContent = """echo "##teamcity[setParameter name='env.PLUGIN_NAME' value='Hello test']""""
        }
        script {
            name = "Test print"
            id = "RUNNER_5"
            scriptContent = """echo "%env.TEST%""""
        }
    }
    steps {
        update<ScriptBuildStep>(2) {
            id = "RUNNER_4"
            clearConditions()
            scriptContent = """
                PLUGIN_NAME=${'$'}(jq -r .name ./package.json)
                PLUGIN_VERSION=${'$'}(jq -r .version ./package.json)
                
                echo "##teamcity[setParameter name='env.PLUGIN_NAME' value=${'$'}PLUGIN_NAME]"
                echo "##teamcity[setParameter name='env.PLUGIN_VERSION' value=${'$'}PLUGIN_VERSION]"
            """.trimIndent()
        }
    }
}
